name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Sphinx
      run: pip install sphinx

    - name: Setup directories
      run: |
        mkdir -p docs/build/html
        mkdir -p docs/source
        
    - name: Initialize Sphinx
      run: |
        if [ ! -f docs/conf.py ]; then
            sphinx-quickstart -q -p "mcmctoolbox" -a "CongYe Wang" -v "1.0" --ext-autodoc --ext-viewcode --sourcedir=source --builddir=build docs
        fi

    - name: Build documentation
      run: |
        sphinx-build -b html docs/source docs/build/html

    - name: Deploy to GitHub Pages
      run: |
        mkdir -p public_html
        cp -r docs/build/html/* public_html/
        touch public_html/.nojekyll
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add public_html/
        git commit -m "Deploy GitHub Pages"
        git push origin +HEAD:gh-pages

    - name: Publish Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public_html
